// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModeloTurnos.Models;

#nullable disable

namespace Actividad04.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241002063901_TurnosPeluqueria")]
    partial class TurnosPeluqueria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.1.24451.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ModeloServicio.Models.DetalleTurno", b =>
                {
                    b.Property<int>("IdTurno")
                        .HasColumnType("int")
                        .HasColumnName("id_turno");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int")
                        .HasColumnName("id_servicio");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("observaciones");

                    b.HasKey("IdTurno", "IdServicio");

                    b.ToTable("DetallesTurno", (string)null);
                });

            modelBuilder.Entity("ModeloServicio.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Monto")
                        .HasColumnType("int")
                        .HasColumnName("costo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<bool>("Promocion")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("bit")
                        .HasColumnName("Promocion");

                    b.HasKey("Id");

                    b.ToTable("Servicios", (string)null);
                });

            modelBuilder.Entity("ModeloServicio.Models.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cancelacion")
                        .HasColumnType("bit")
                        .HasColumnName("Cancelacion");

                    b.Property<string>("Cliente")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cliente");

                    b.Property<DateTime>("Fecha")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<TimeSpan>("Hora")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("time")
                        .HasColumnName("hora");

                    b.Property<string>("MotivoCancelacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("motivo_cancelacion");

                    b.HasKey("Id");

                    b.ToTable("Turnos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
